import os
import sqlite3
import uuid
import datetime
import math
import re
import hashlib
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

DB_PATH = "provenance_guard.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            content_id TEXT PRIMARY KEY,
            creator_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            attribution TEXT NOT NULL,
            confidence REAL NOT NULL,
            llm_score REAL NOT NULL,
            stylometric_score REAL NOT NULL,
            entropy_score REAL NOT NULL,
            metadata_score REAL NOT NULL,
            status TEXT NOT NULL,
            text_excerpt TEXT NOT NULL,
            certificate_id TEXT,
            appeal_reasoning TEXT
        )
    """)
    conn.commit()
    conn.close()

init_db()

def get_llm_signal_score(text: str) -> float:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key or api_key == "gsk_your_actual_groq_api_key_here":
        return 0.5
    
    try:
        client = Groq(api_key=api_key)
        prompt = (
            "Analyze the following text and determine the probability that it was generated by an AI. "
            "Respond ONLY with a single floating-point number between 0.00 and 1.00, where 1.00 means definitively AI.\n\n"
            f"Text: {text}"
        )
        response = client.chat.completions.create(
            model="meta-llama/llama-4-scout-17b-16e-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=10
        )
        raw_val = response.choices[0].message.content.strip()
        match = re.search(r"0\.\d+|1\.0|0", raw_val)
        if match:
            return float(match.group(0))
        return 0.5
    except Exception as e:
        return 0.5

def get_stylometric_signal_score(text: str) -> float:
    words = re.findall(r'\b\w+\b', text.lower())
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    
    if not words:
        return 0.5
    
    # Informal / Conversational markers indicate lower probability of AI output
    informal_markers = ["i", "my", "was", "me", "we", "noticed", "yeah", "stuff", "walked", "went", "got", "cool"]
    marker_count = sum(1 for w in words if w in informal_markers)
    informal_ratio = marker_count / len(words)
    
    # Type-Token Ratio
    ttr = len(set(words)) / len(words)
    
    # Natural human variance score calculation
    human_likelihood = (0.6 * informal_ratio) + (0.4 * ttr)
    ai_stylometric_score = max(0.05, min(0.95, 1.0 - human_likelihood))
    return round(ai_stylometric_score, 2)

def get_entropy_signal_score(text: str) -> float:
    if not text:
        return 0.5
    
    prob = [float(text.count(c)) / len(text) for c in set(text)]
    entropy = -sum([p * math.log2(p) for p in prob])
    
    # Organic text typically exhibits non-uniform character entropy
    if 3.8 <= entropy <= 4.8:
        return 0.20
    return 0.70

def get_metadata_signal_score(metadata: dict) -> float:
    if not metadata:
        return 0.5
    
    software = str(metadata.get("software", "")).lower()
    ai_keywords = ["midjourney", "stable diffusion", "dall-e", "chatgpt", "generative"]
    
    if any(kw in software for kw in ai_keywords):
        return 0.95
    if metadata.get("camera_model") or metadata.get("exif_data"):
        return 0.10
    
    return 0.5

def resolve_attribution_and_label(confidence: float):
    if confidence >= 0.70:
        attribution = "likely_ai"
        label = (
            "AI-Generated Content: This submission exhibits strong statistical and structural characteristics "
            "typical of AI language models. Context provided for platform transparency."
        )
    elif confidence <= 0.39:
        attribution = "likely_human"
        label = (
            "Human-Authored Content: Analysis indicates organic structural variance and stylistic "
            "characteristics consistent with human writing."
        )
    else:
        attribution = "uncertain"
        label = (
            "Uncertain Attribution: Detection signals yielded mixed or non-conclusive results. "
            "Placed in neutral status to protect author attribution."
        )
    return attribution, label

def generate_provenance_certificate(content_id: str, text: str) -> str:
    payload = f"{content_id}:{text[:50]}"
    hash_digest = hashlib.sha256(payload.encode('utf-8')).hexdigest()[:16]
    return f"PROV-HUMAN-{content_id[:8]}-{hash_digest.upper()}"

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit_content():
    data = request.get_json() or {}
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()
    image_metadata = data.get("image_metadata", {})
    
    if not text or not creator_id:
        return jsonify({"error": "Missing required fields: 'text' and 'creator_id'"}), 400
    
    content_id = str(uuid.uuid4())
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    llm_score = get_llm_signal_score(text)
    sty_score = get_stylometric_signal_score(text)
    entropy_score = get_entropy_signal_score(text)
    meta_score = get_metadata_signal_score(image_metadata)
    
    if os.getenv("GROQ_API_KEY") and os.getenv("GROQ_API_KEY") != "gsk_your_actual_groq_api_key_here":
        confidence = round((0.45 * llm_score) + (0.30 * sty_score) + (0.25 * entropy_score), 2)
    else:
        # Balanced score distribution without external LLM API key
        confidence = round((0.55 * sty_score) + (0.45 * entropy_score), 2)
        
    attribution, label_text = resolve_attribution_and_label(confidence)
    status = "classified"
    
    certificate_id = None
    if confidence <= 0.30:
        certificate_id = generate_provenance_certificate(content_id, text)
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO audit_log 
        (content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, entropy_score, metadata_score, status, text_excerpt, certificate_id, appeal_reasoning)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (content_id, creator_id, timestamp, attribution, confidence, llm_score, sty_score, entropy_score, meta_score, status, text[:100], certificate_id, None))
    conn.commit()
    conn.close()
    
    response_payload = {
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "llm_score": llm_score,
            "stylometric_score": sty_score,
            "entropy_score": entropy_score,
            "metadata_score": meta_score
        },
        "label": label_text,
        "status": status
    }
    
    if certificate_id:
        response_payload["provenance_certificate"] = {
            "certificate_id": certificate_id,
            "badge": "Verified Human Credential: Earned via multi-signal organic provenance validation."
        }
        
    return jsonify(response_payload), 200

@app.route("/appeal", methods=["POST"])
def submit_appeal():
    data = request.get_json() or {}
    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()
    
    if not content_id or not reasoning:
        return jsonify({"error": "Missing required fields: 'content_id' and 'creator_reasoning'"}), 400
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT content_id FROM audit_log WHERE content_id = ?", (content_id,))
    row = cursor.fetchone()
    
    if not row:
        conn.close()
        return jsonify({"error": "Content ID not found in audit log."}), 404
    
    cursor.execute("""
        UPDATE audit_log
        SET status = 'under_review', appeal_reasoning = ?
        WHERE content_id = ?
    """, (reasoning, content_id))
    conn.commit()
    conn.close()
    
    return jsonify({
        "message": "Appeal successfully submitted and recorded.",
        "content_id": content_id,
        "status": "under_review"
    }), 200

@app.route("/log", methods=["GET"])
def get_audit_log():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT 20")
    rows = cursor.fetchall()
    conn.close()
    
    entries = [dict(row) for row in rows]
    return jsonify({"entries": entries}), 200

@app.route("/analytics/data", methods=["GET"])
def get_analytics():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute("SELECT COUNT(*) FROM audit_log")
    total_submissions = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM audit_log WHERE attribution = 'likely_ai'")
    ai_count = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM audit_log WHERE attribution = 'likely_human'")
    human_count = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM audit_log WHERE attribution = 'uncertain'")
    uncertain_count = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM audit_log WHERE status = 'under_review'")
    appeals_count = cursor.fetchone()[0]
    
    cursor.execute("SELECT AVG(confidence) FROM audit_log")
    avg_confidence = cursor.fetchone()[0] or 0.0
    
    conn.close()
    
    appeal_rate = round((appeals_count / total_submissions * 100), 2) if total_submissions > 0 else 0.0
    
    return jsonify({
        "total_submissions": total_submissions,
        "classifications": {
            "likely_ai": ai_count,
            "likely_human": human_count,
            "uncertain": uncertain_count
        },
        "appeals_count": appeals_count,
        "appeal_rate_percentage": appeal_rate,
        "average_confidence_score": round(avg_confidence, 2)
    }), 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5001, debug=True)